### ISSUE TITLE
SDEdit doesn't parse UTF-8 script files with BOM correctly

### ISSUE THREAD

**Issue by school510587** [sdedit/sdedit#12]
Sometimes the input script contains non-ASCII characters, and it is inevitable to use UTF-8 encoding.
However, notepad on Windows always adds a BOM at the beginning of an UTF-8 text file.
When such file is given as the input, SDEdit outputs the following error message:

Exception in thread "main" net.sf.sdedit.error.SyntaxError: not a valid object declaration - ':' missing
	at net.sf.sdedit.text.TextHandler.nextObject(TextHandler.java:325)
	at net.sf.sdedit.diagram.SequenceDiagram.readObjects(SequenceDiagram.java:433)
	at net.sf.sdedit.diagram.SequenceDiagram.generate(SequenceDiagram.java:356)
	at net.sf.sdedit.diagram.SequenceDiagram.generate(SequenceDiagram.java:331)
	at net.sf.sdedit.diagram.SequenceDiagramFactory.generateDiagram(SequenceDiagramFactory.java:82)
	at net.sf.sdedit.Main.createImage(Main.java:283)
	at net.sf.sdedit.Main.main(Main.java:135)

Would SDEdit accept UTF-8 script files with BOM? Thanks.

**Comment by sdedit** [comment]
Date:   2019-01-04 (Fri, 04 Jan 2019)

  Changed paths:
    M QSD/src/main/java/net/sf/sdedit/editor/plugin/AbstractFileHandler.java

  Log Message:
  -----------
  ignore byte order mark
